import "./globals.css";
import { Inter } from "next/font/google";
import style from "./page.module.css"
import {Metadata} from "next";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className={style.container}>
        {children}
    </div>
    </body>
    </html>
  );
}
